---
roleName: Contributor
assignments:
- name: spn-staging-vuln-scan-archiver
  type: ServicePrincipal
  scope: "/resourceGroups/rg-vuln-mgmt-sandbox/providers/Microsoft.Storage/storageAccounts/savulnscanarchiver"
