---
roleName: Reader
assignments:
- name: azure-nonprod-security-vulnmanagement-contributor
  type: Group
- name: spn-staging-vuln-scan-archiver
  type: ServicePrincipal
  scope: "/resourceGroups/rg-vuln-mgmt-sandbox/providers/Microsoft.Storage/storageAccounts/savulnscanarchiver"