---
assignableScopes:
- "/providers/Microsoft.Management/managementGroups/398a6654-997b-47e9-b12b-9515b896b4de"
description: Used to read effective route tables from NICs for network troubleshooting
name: Azure Effective Route Table Reader
permissions:
- notDataActions: []
  dataActions: []
  notActions: []
  actions:
  - Microsoft.Network/networkInterfaces/effectiveRouteTable/action
