---
assignableScopes:
- "/providers/Microsoft.Management/managementGroups/398a6654-997b-47e9-b12b-9515b896b4de"
description: This is a custom role to allow managing Azure AD Diagnostic Settings
name: azure-ad-diagnostic-settings
permissions:
- notDataActions: []
  dataActions: []
  notActions: []
  actions:
  - microsoft.aadiam/diagnosticSettings/*
