---
assignableScopes:
- "/providers/Microsoft.Management/managementGroups/398a6654-997b-47e9-b12b-9515b896b4de"
description: Used by Azure Policy SMIs to control Deployments
name: Azure Deployments Administrator
permissions:
- notDataActions: []
  dataActions: []
  notActions: []
  actions:
  - Microsoft.Resources/deployments/*
