---
assignableScopes:
- "/providers/Microsoft.Management/managementGroups/398a6654-997b-47e9-b12b-9515b896b4de"
description: Used to Provision Azure Subscription and Related Resources
name: Azure Subscription Provisioner
permissions:
- notDataActions: []
  dataActions: []
  notActions: []
  actions:
  - Microsoft.Management/managementGroups/read
  - Microsoft.Management/managementGroups/write
  - Microsoft.Management/managementGroups/subscriptions/read
  - Microsoft.Management/managementGroups/subscriptions/write
  - Microsoft.Resources/tags/*
  - Microsoft.Authorization/roleAssignments/*
